version: '3.8'

services:

  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ./ollama/ollama_data:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
      - OLLAMA_HOST=0.0.0.0
    networks:
      - localbridge
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]


  open-webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    depends_on:
      ollama:
        condition: service_started
    volumes:
      - openwebui_data:/app/backend/data
    networks:
      - localbridge
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      - OLLAMA_HOST=${OLLAMA_HOST}
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  openwebui_data: {}

networks:
  localbridge:
    internal: false
